# Generated by Django 5.0.6 on 2026-03-20 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDENTE_VALIDACAO', 'Pendente Validação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE_VALIDACAO', max_length=30)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ATESTADO_MATRICULA', 'Atestado de Matrícula')], default='ATESTADO_MATRICULA', max_length=30)),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('verificado', models.BooleanField(default=False)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('verificado_em', models.DateTimeField(blank=True, null=True)),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_verificados', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documento', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='events.lote')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
                'unique_together': {('pedido', 'lote')},
            },
        ),
    ]
