# Generated by Django 5.0.6 on 2026-03-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=20)),
                ('metodo', models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito')], max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('preference_id', models.CharField(blank=True, max_length=100)),
                ('external_reference', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_pix', models.TextField(blank=True)),
                ('url_pagamento', models.URLField(blank=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_payload', models.JSONField(default=dict)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='orders.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
