# Generated by Django 5.0.6 on 2026-03-20 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('CALOURO', 'Calouro'), ('VETERANO', 'Veterano'), ('EXTERNO', 'Externo')], max_length=20)),
                ('status', models.CharField(choices=[('VALIDO', 'Válido'), ('UTILIZADO', 'Já Utilizado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='VALIDO', max_length=20)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/')),
                ('utilizado_em', models.DateTimeField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingressos', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingressos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingresso',
                'verbose_name_plural': 'Ingressos',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'evento', 'uuid')},
            },
        ),
    ]
